version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      RADARR_URL: ${RADARR_URL}
      RADARR_API_KEY: ${RADARR_API_KEY}
      SONARR_URL: ${SONARR_URL}
      SONARR_API_KEY: ${SONARR_API_KEY}
      TMDB_API_KEY: ${TMDB_API_KEY}
      REDIS_IP: ${REDIS_IP}
    depends_on:
      - redis
      - worker

  worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    environment:
      RADARR_URL: ${RADARR_URL}
      RADARR_API_KEY: ${RADARR_API_KEY}
      SONARR_URL: ${SONARR_URL}
      SONARR_API_KEY: ${SONARR_API_KEY}
      TMDB_API_KEY: ${TMDB_API_KEY}
      REDIS_IP: ${REDIS_IP}
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
