# Dockerfile.celery

# Usar una imagen base de Python
FROM python:3.9-slim

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar el archivo requirements.txt al contenedor
COPY requirements.txt requirements.txt

# Instalar las dependencias del proyecto
RUN pip install -r requirements.txt

# Copiar el resto de los archivos de la aplicación al contenedor
COPY . .

# Comando para ejecutar Celery
CMD ["celery", "-A", "tasks", "worker", "--loglevel=info", "--beat"]
