version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./:/app/config
    depends_on:
      - redis
      - worker

  worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    volumes:
      - ./:/app/config
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
      
