FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . .

COPY config.json /app/config/config.json.default

CMD ["celery", "-A", "tasks", "worker", "--loglevel=info", "--beat"]
